[package]
name = "bw-r-rt-example"
version = "0.1.0"
edition = "2021"
license = " BSL-1.0 license"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = "0.3.5"
tc37x = { path = "../tc37x", features = ["scu"] }